name: 'Giphy PR Comments'
description: 'Add a Giphy GIG Comment to new pull request'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  giphy-api-token:
    description: 'Giphy API Token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.giphy-api-token }}


# Ref: https://docs.github.com/en/actions/tutorials/use-containerized-services/create-a-docker-container-action